spring:
  profiles:
    active:
      - dev
---
server:
  port: 7001  #注册中心占用7001端口
spring:
  profiles: dev
  application:
    name: springcloud-config-eureka-client
eureka:
  client:
    service-url:
      defaultZone:  http://eureka7001.com:7001/eureka/
    register-with-eureka: false #当前的eureka server 不注册进eureka服务列表中
    fetch-registry: false #不通过eureka获取注册信息
  instance:
    instance-id: springcloud-config-eureka-client-7001
    hostname: eureka7001.com
---
server:
  port: 7001  #注册中心占用7001端口
spring:
  profiles: test
  application:
    name: springcloud-config-eureka-client
eureka:
  client:
    service-url:
      defaultZone:  http://eureka7001.com:7001/eureka/
    register-with-eureka: false #当前的eureka server 不注册进eureka服务列表中
    fetch-registry: false #不通过eureka获取注册信息
  instance:
    instance-id: springcloud-config-eureka-client-7001
    hostname: eureka7001.com