spring:
  profiles:
    active:
      - dev
---
server:
  port: 8201
spring:
  profiles: dev
  application:
    name: springcloud-config-client
eureka:
  client:
    service-url:
      defaultZone: http://eureka-dev.com:7001/eureka/
---
spring:
  profiles: test
  application:
    name: springcloud-config-client
server:
  port: 8202
eureka:
  client:
    service-url:
      defaultZone: http://eureka-test.com:7001/eureka/